# Generated by Django 3.2.12 on 2023-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='font_size',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
