# Generated by Django 3.2.12 on 2023-10-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='font_size',
        ),
    ]
